on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  download-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 'Setup Deno'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.31.1
      - name: 'Prepare Directories'
        run: mkdir -p steam/events
      - name: 'Download Events'
        run: deno run --allow-all .github/workflows-scripts/download-events.ts
      - name: '`git status`'
        id: git-status
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: '`git config`'
        if: steps.git-status.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: '`git push`'
        if: steps.git-status.outputs.modified == 'true'
        run:  |
          git add -A
          git commit -m '[automated commit] update files'
          git push